/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.7/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    `maven-publish`
    id("io.freefair.lombok") version "9.5.0"
    id("com.gradleup.shadow") version "9.4.2"
    jacoco
    id("com.github.spotbugs") version "6.5.6"
    checkstyle
    id("org.cyclonedx.bom") version "3.2.4"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api(libs.commons.math3)
    api("com.google.guava:guava:33.1.0-jre")

    // AWS S3 Start: https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/setup-project-gradle.html
    api(platform("software.amazon.awssdk:bom:2.25.41"))
    api("software.amazon.awssdk:s3")
    api("software.amazon.awssdk:sso")
    api("software.amazon.awssdk:ssooidc")
    api("software.amazon.awssdk:sts")

    // Logging
    api(platform("org.apache.logging.log4j:log4j-bom:2.23.1"))
    api("org.apache.logging.log4j:log4j-api")
    api("org.apache.logging.log4j:log4j-core")
    
    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    implementation(libs.guava)
    implementation("org.apache.commons:commons-lang3:3.0")
    implementation("com.jayway.jsonpath:json-path:2.9.0")
    implementation("io.github.resilience4j:resilience4j-retry:2.2.0")
    implementation(platform("com.fasterxml.jackson:jackson-bom:2.17.0"))
    implementation("com.fasterxml.jackson.core:jackson-core")
    implementation("com.fasterxml.jackson.core:jackson-annotations")
    implementation("com.fasterxml.jackson.core:jackson-databind")
    implementation("commons-codec:commons-codec:1.17.1")
    implementation("commons-beanutils:commons-beanutils:1.9.4")
    implementation("org.apache.commons:commons-configuration2:2.11.0")

    testImplementation(platform("org.junit:junit-bom:5.10.2"))
    testImplementation("org.junit.jupiter:junit-jupiter")

    testImplementation("org.junit.jupiter:junit-jupiter-api:5.8.1")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.8.1")
    testImplementation("org.mockito:mockito-core:5.11.0")
    testImplementation("org.mockito:mockito-junit-jupiter:5.11.0")

    spotbugsPlugins("com.h3xstream.findsecbugs:findsecbugs-plugin:1.12.0")
    spotbugsSlf4j("org.slf4j:slf4j-simple:2.0.12")
}

jacoco {
    toolVersion = "0.8.15" // Use the latest version available
}

tasks.jacocoTestReport {
    classDirectories.setFrom(
        files(classDirectories.files.map {
            fileTree(it) {
                exclude(
                    "**/com/amazon/demanddriventrafficevaluator/repository/entity/**",
                    "**/Builder*",
                    "**/*\$Builder*",
                    "**/com/amazon/demanddriventrafficevaluator/evaluation/evaluator/Response.class",
                    "**/com/amazon/demanddriventrafficevaluator/evaluation/evaluator/Signal.class",
                    "**/com/amazon/demanddriventrafficevaluator/evaluation/evaluator/Slot.class",
                    "**/LocalCacheBuilderConfig.class",
                    "**/*Input*.*",
                    "**/*Output*.*",
                    "**/exception/**"
                )
            }
        })
    )
    reports {
        xml.required.set(true)
        csv.required.set(false)
        html.required.set(true)
    }
}

tasks.test {
    finalizedBy(tasks.jacocoTestReport)
}

tasks.jacocoTestCoverageVerification {
    violationRules {
        rule {
            limit {
                minimum = "0.1".toBigDecimal()
            }
        }
    }
}

spotbugs {
    toolVersion.set("4.10.2")
    ignoreFailures.set(false)
    showProgress.set(true)
    effort.set(com.github.spotbugs.snom.Effort.MAX)
    reportLevel.set(com.github.spotbugs.snom.Confidence.HIGH)
    excludeFilter.set(file("config/spotbugs/spotbugs-exclude.xml"))
}

tasks.withType<com.github.spotbugs.snom.SpotBugsTask>().configureEach {
    reports.create("html") {
        required.set(true)
        outputLocation.set(layout.buildDirectory.file("reports/spotbugs/${project.name}.html"))
        setStylesheet("fancy-hist.xsl")
    }
    reports.create("xml") {
        required.set(true)
        outputLocation.set(layout.buildDirectory.file("reports/spotbugs/${project.name}.xml"))
    }
}

checkstyle {
    toolVersion = "8.45"
    configFile = file("config/checkstyle/checkstyle.xml")
    isIgnoreFailures = false
    isShowViolations = true
}

tasks.withType<Checkstyle>().configureEach {
    reports {
        xml.required.set(false)
	xml.outputLocation.set(layout.buildDirectory.file("reports/checkstyle/${project.name}.xml"))
        html.required.set(true)
	html.outputLocation.set(layout.buildDirectory.file("reports/checkstyle/${project.name}.html"))
    }
}

tasks.check {
    dependsOn(tasks.jacocoTestCoverageVerification)
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use JUnit4 test framework
            useJUnitJupiter()
        }
    }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

tasks.register("buildNoTests") {
    dependsOn("build")
    tasks.findByName("test")?.enabled = false
}

tasks.javadoc {
    options {
        (this as StandardJavadocDocletOptions).apply {
            addStringOption("Xdoclint:none", "-quiet")
            encoding = "UTF-8"
            charSet = "UTF-8"
            author(true)
            version(true)
            use(true)
            windowTitle = project.name
            header = "${project.name} API"
            bottom = "Copyright © 2024 Amazon.com, Inc. or its affiliates"
            links("https://docs.oracle.com/en/java/javase/${JavaVersion.current().majorVersion}/docs/api/")
        }
    }
}

java {
        withJavadocJar()
        withSourcesJar()
}

tasks {
    named<com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar>("shadowJar") {
        archiveClassifier.set("fat")
        destinationDirectory.set(layout.buildDirectory.dir("libs"))
        configurations = listOf(project.configurations.runtimeClasspath.get())

        mergeServiceFiles()

    }
    register("buildAndPrintJarInfo") {
        dependsOn("spotbugsMain", "spotbugsTest", "shadowJar")
        doLast {
            val jarFile = named<com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar>("shadowJar").get().archiveFile.get().asFile
            val javadocDir = layout.buildDirectory.dir("docs/javadoc").get().asFile
            val indexHtmlFile = javadocDir.resolve("index.html")
            val spotbugsReport = layout.buildDirectory.file("reports/spotbugs/${project.name}.html").get().asFile

            logger.lifecycle("==========================================")
            logger.lifecycle("Fat JAR created at: ${jarFile.absolutePath}")
            logger.lifecycle("Fat JAR size: ${jarFile.length() / 1024} KB")
            logger.lifecycle("Javadoc generated at: ${indexHtmlFile.absolutePath}")
            logger.lifecycle("SpotBugs report generated at: ${spotbugsReport.absolutePath}")
            logger.lifecycle("==========================================")
        }
    }

    build {
        dependsOn("buildAndPrintJarInfo")
        dependsOn("javadoc")
    }

    test {
        finalizedBy(jacocoTestReport)
    }
}

project.group = "com.amazon.demanddriventrafficevaluator"
configure<PublishingExtension> {
publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
        repositories {
                mavenLocal()
                maven {
                        name = "GitHub"
                        url = uri("https://maven.pkg.github.com/${project.findProperty("gpr.repo")}")
                        credentials {
                                username = project.findProperty("gpr.user").toString()
                                password = project.findProperty("gpr.key").toString()
                        }
                }
        }
}
